- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.12'

- name: Check repository contents
  run: |
    pwd
    ls -l

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then 
      pip install -r requirements.txt 
    else
      echo "requirements.txt not found"
      exit 1
    fi


- name: Install dependencies
  working-directory: ./path/to/your/project
  run: |
    pip install -r requirements.txt












name: Daily Python Script

on:
  schedule:
    # Runs daily at 6:00 AM UTC
    - cron: "02 8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if any)
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Script
        run: |
          python Amz_Webscrapping (2).py
