name: Daily Python Script

on:
  schedule:
    # Runs daily at 9:06 AM UTC
    - cron: "06 9 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: List files (debugging step, optional)
      - name: List files in the repository
        run: ls -la

      # Step 4: Install dependencies (if requirements.txt exists)
      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found, skipping."
          fi

      # Step 5: Run the Python script
      - name: Run Script
        run: |
          python "Amz_Webscrapping (2).py"
